import { Worker, Job } from 'bullmq'
import { prisma } from '@singr/db'
import { emitToShow } from '../ws/ws-server.js'
import pino from 'pino'

const logger = pino()
const redisUrl = process.env.REDIS_URL || 'redis://localhost:6380'
const parsed = new URL(redisUrl)
const connection = {
  host: parsed.hostname || 'localhost',
  port: parsed.port ? parseInt(parsed.port, 10) : 6379,
  username: parsed.username || undefined,
  password: parsed.password ? decodeURIComponent(parsed.password) : undefined,
  maxRetriesPerRequest: null,
}

export const songSyncWorker = new Worker(
  'song-sync',
  async (job: Job<{ systemId: string }>) => {
    const { systemId } = job.data
    logger.info(`🔄 Worker running shadow-swap transaction for system: ${systemId}`)

    try {
      await prisma.$transaction(async (tx) => {
        // 1. Delete live songs for this system
        await tx.song.deleteMany({
          where: { systemsId: systemId },
        })

        // 2. Fetch all shadow songs for this system
        const shadowSongs = await tx.songShadow.findMany({
          where: { systemsId: systemId },
        })

        logger.info(`📋 Copying ${shadowSongs.length} songs from shadow to live...`)

        // 3. Copy to live songs table (searchVector is auto-generated by DB GIN trigger)
        await tx.song.createMany({
          data: shadowSongs.map((shadow) => ({
            systemsId: systemId,
            artist: shadow.artist,
            title: shadow.title,
            brand: shadow.brand,
          })),
        })

        // 4. Clean up shadow table
        await tx.songShadow.deleteMany({
          where: { systemsId: systemId },
        })

        // 5. If there's an active show, set isAccepting to true and increment serial counter
        const activeShow = await tx.show.findFirst({
          where: {
            activeSystemsId: systemId,
            deletedAt: null,
          },
        })

        if (activeShow) {
          const updatedShow = await tx.show.update({
            where: { id: activeShow.id },
            data: {
              isAccepting: true,
              serialCounter: { increment: 1 },
            },
          })

          // 6. Broadcast real-time status update to show attendees
          emitToShow(activeShow.id, 'songs_synced', {
            isAccepting: updatedShow.isAccepting,
            serialCounter: updatedShow.serialCounter,
          })
          
          logger.info(`✅ Show ${activeShow.slug} is active, accepting requests, and serial incremented`)
        }
      })
      logger.info(`✅ Shadow-swap completed successfully for system: ${systemId}`)
    } catch (error: any) {
      logger.error(error instanceof Error ? error : new Error(String(error)), `❌ Shadow-swap transaction failed for system: ${systemId}`)
      throw error
    }
  },
  {
    connection,
    concurrency: 2, // Limit to 2 concurrent sync processes to prevent CPU/database spikes
  }
)

songSyncWorker.on('completed', (job) => {
  logger.info(`🎉 Songbook sync job ${job.id} completed successfully!`)
})

songSyncWorker.on('failed', (job, err) => {
  logger.error(err, `❌ Songbook sync job ${job?.id} failed`)
})
